# Changes here will be overwritten by Copier
_commit: v1.4.0
_src_path: gh://lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: false
custom_install: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: qp_flexzboost
preferred_linter: black
project_license: MIT
project_name: qp_flexzboost
use_gitlfs: none
use_isort: true
