# Changes here will be overwritten by Copier
_commit: 1.2.0
_src_path: gh://lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
module_name: qp_flexzboost
preferred_linter: pylint
project_name: qp_flexzboost
use_isort: true
